/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Transaction {
  export type TransferStructStruct = {
    sender: AddressLike;
    receiver: AddressLike;
    amount: BigNumberish;
    message: string;
    timestamp: BigNumberish;
    keyword: string;
  };

  export type TransferStructStructOutput = [
    sender: string,
    receiver: string,
    amount: bigint,
    message: string,
    timestamp: bigint,
    keyword: string
  ] & {
    sender: string;
    receiver: string;
    amount: bigint;
    message: string;
    timestamp: bigint;
    keyword: string;
  };
}

export interface TransactionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addToBlockchain"
      | "getAllTransactions"
      | "getTransactionCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransactionAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addToBlockchain",
    values: [AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addToBlockchain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
}

export namespace TransactionAddedEvent {
  export type InputTuple = [
    from: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    message: string,
    timestamp: BigNumberish,
    keyword: string
  ];
  export type OutputTuple = [
    from: string,
    receiver: string,
    amount: bigint,
    message: string,
    timestamp: bigint,
    keyword: string
  ];
  export interface OutputObject {
    from: string;
    receiver: string;
    amount: bigint;
    message: string;
    timestamp: bigint;
    keyword: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Transaction extends BaseContract {
  connect(runner?: ContractRunner | null): Transaction;
  waitForDeployment(): Promise<this>;

  interface: TransactionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToBlockchain: TypedContractMethod<
    [
      receiver: AddressLike,
      amount: BigNumberish,
      message: string,
      keyword: string
    ],
    [void],
    "nonpayable"
  >;

  getAllTransactions: TypedContractMethod<
    [],
    [Transaction.TransferStructStructOutput[]],
    "view"
  >;

  getTransactionCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToBlockchain"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      amount: BigNumberish,
      message: string,
      keyword: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllTransactions"
  ): TypedContractMethod<
    [],
    [Transaction.TransferStructStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransactionCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "TransactionAdded"
  ): TypedContractEvent<
    TransactionAddedEvent.InputTuple,
    TransactionAddedEvent.OutputTuple,
    TransactionAddedEvent.OutputObject
  >;

  filters: {
    "TransactionAdded(address,address,uint256,string,uint256,string)": TypedContractEvent<
      TransactionAddedEvent.InputTuple,
      TransactionAddedEvent.OutputTuple,
      TransactionAddedEvent.OutputObject
    >;
    TransactionAdded: TypedContractEvent<
      TransactionAddedEvent.InputTuple,
      TransactionAddedEvent.OutputTuple,
      TransactionAddedEvent.OutputObject
    >;
  };
}
